FROM golang:1.23-alpine

WORKDIR /app

# 1. Copiar solo definiciones de dependencias
COPY go.mod go.sum ./
RUN go mod download

# 2. Copiar SOLO los archivos de código (NO los datos)
COPY *.go ./

# 3. Compilar
RUN go build -o coordinador coordinador.go rec.go database.go

# 4. Ejecutar
CMD ["./coordinador"]